---
- hosts: all
  become: true
  tasks:
  - name: install nginx & certbot
    apt:
      name:
        - certbot
        - python-certbot-nginx
        - nginx
      state: latest
      update_cache: true
  - name: Start NGINX Service
    service:
      name: nginx
      state: started
  - name: check for certificates
    stat:
      path: /etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem
    register: certificate
  - name: configure TLS
    shell: "certbot certonly --nginx -n --agree-tos --email test@gmail.com --domains '{{ inventory_hostname }}'"
    when: certificate.stat.exists == False
    template:
      src: ../resources/default
      dest: /etc/nginx/sites-available/default
  - name: reload nginx service
    service:
      name: nginx
      state: reloaded
